#SPDX-License-Identifier: MIT-0
---
- name: Install AD-Domain-Services
  win_feature:
    name: AD-Domain-Services
    include_management_tools: yes
    state: present

- name: Promote server to DC
  win_domain:
    dns_domain_name: "{{ domain_name }}"
    safe_mode_password: "{{ safe_mode_password }}"
    domain_admin_user: "{{ ansible_user }}"
    domain_admin_password: "{{ ansible_password }}"
    state: domain_controller
    create_dns_delegation: no
