---
- hosts: windows2022
  gather_facts: false
  vars_files:
    - ./domain_users.yml
  tasks:
  - name: Add Users
    win_domain_user:
      name: "{{ item.key }}"
      firstname: "{{ item.value.firstname}}"
      surname: "{{ item.value.surname}}"
      password: "{{ item.value.password }}"
      password_expired: yes
      attributes:
        displayName: '{{ item.value.firstname }} {{ item.value.surname }}'
    loop: "{{ lookup('dict', users) }}"