---
- name: Add admin user to servers
  hosts: testwebserver
  become: yes
  gather_facts: false

  vars_prompt:
    - name: password
      prompt: "Please enter a password for servmanager:"
      private: true
      encrypt: sha512_crypt
      confirm: true
      salt_size: 16

  tasks:
    - name: Add user
      user:
        name: "servmanager"
        password: "{{ password }}"
        comment: "Server manager"
        uid: 1040
        create_home: true
        shell: /bin/bash
        groups: wheel
        append: yes