---
- name: Install httpd and set welcomepage
  hosts: testwebserver,productiewebservers
  become: yes
  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: present

    - name: Make sure httpd is started
      systemd:
        name: httpd
        state: started
        enabled: yes

    - name: Create welcomepage
      copy:
        dest: /var/www/html/index.html
        content: |
          <html>
          <head><title>Welkom bij KlantA</title></head>
          <body>
          <h1>Welkom bij KlantA! Gemaakt door 552512</h1>
          <p>Deze webserver is succesvol geïnstalleerd met Ansible</p>
          </body>
          </html>
