---
- name: Kies het type website
  hosts: testwebserver,productiewebservers
  gather_facts: no
  become: yes

  vars_prompt:
    - name: website_type
      prompt: "Welk type website wil je installeren? (wordpress, joomla, httpd)"
      private: no

  tasks:
    - name: Installeer WordPress
      include_tasks: install_wordpress.yml
      when: website_type == "wordpress"

    - name: Installeer Joomla
      include_tasks: install_joomla.yml
      when: website_type == "joomla"

    - name: Installeer Apache
      include_tasks: install_httpd.yml
      when: website_type == "httpd"
