---
- name: Kies het type website
  hosts: productiewebservers
  gather_facts: true
  become: true

  vars_prompt:
    - name: website_type
      prompt: "Welk type website wil je installeren? (wordpress, joomla, httpd)"
      private: no

  roles:
    - role: deploy-docker
    - role: wordpress
      when: website_type == "wordpress"

    - role: joomla
      when: website_type == "joomla"

    - role: custom-website
      when: website_type == "httpd"
