---
- name: Deploy MySQL server
  docker_container:
    image: mysql:8
    name: joomladb
    env:
      MYSQL_ROOT_PASSWORD: "{{ joomla_mysql_root_password }}"
      MYSQL_PASSWORD: "{{ joomla_mysql_user_password }}"
      MYSQL_DATABASE: "{{ joomla_mysql_database }}"
      MYSQL_USER: "{{ joomla_mysql_user }}"
    ports:
      - "3306:3306"
    volumes:
      - "/var/lib/{{ joomla_volume }}:/var/lib/mysql"
    restart_policy: always

- name: Start een Joomla container
  docker_container:
    name: joomla
    image: joomla
    links: 
      - "joomladb:db"
    ports:
      - "80:80"
    volumes:
      - "/var/www/joomla:/var/www/html"
    env:
      JOOMLA_DB_HOST: "joomladb:3306"
      JOOMLA_DB_USER: "{{ joomla_mysql_user }}"
      JOOMLA_DB_PASSWORD: "{{ joomla_mysql_user_password }}"
      JOOMLA_DB_NAME: "{{ joomla_mysql_database }}"
    restart_policy: always
