---
- name: install/start webserver
  hosts: servers
  tasks:
  - name: install httdp
    become: true
    yum:
      name: httpd
      state: latest
  - name: ensure httpd running
    become: true
    service:
      name: httpd
      state: started